### PR TITLE
Accept async functions

### PR DESCRIPTION
**Pull request by muan**
https://github.com/github/github/pull/111598#discussion_r272512629 & https://github.com/facebook/flow/issues/5882.

As far as I can see TypeScript does not seem to care? 🤔  

cc @josh

### CODE REVIEW

**Comment by josh** [comment]
My original thinking here is that I considered these async callbacks a footgun.

Accepting a promise return value _may_ indicate that caller will wait on that return--which selector-observer can not implement correctly.

Internally, selector-observer preserves the invariant that a `remove` always follows `add`. You'll always get `add`, `remove`, `add`, `remove`. But never see any behavior like `add`, `add`, `remove`, `remove` on a single element. This is easier promise given a single event loop tick. Things seem a little harder to predicate once async code is introduced.

Consider:

```js
// using a singleton element to simplify the example
// invariant: count will always been 0 or 1
let count = 0

observe("#singleton", {
  add() {
    count++
  },
  remove() {
    count--
  }
})
```

When adding `async` I'd expect the behavior to be preserved. And it kinda does because of the nature of async functions being implemented called.

```js
let count = 0
observe("#singleton", {
  async add() {
    count++
  },
  async remove() {
    count--
  }
})
```

But once you though an await into the mix (which you probably are if you want to use `async`), then the invariant starts to break.

```js
let count = 0
observe("#singleton", {
  async add() {
    await madness()
    count++
  },
  async remove() {
    count--
  }
})
```

In these cases, I think it's better that the user introduce their own async IIFE.

**Comment by muan** [comment]
That makes sense. Would you be open to only accepting async on `InitializerCallback` then? That is what the linked use case needs.

**Comment by josh** [comment]
> Would you be open to only accepting async function on `InitializerCallback` then?

I think that's another confusing case. The initializer hook looks for a truthy value returned from the initialize. In the current case any `null` or `void` would be correctly ignored. But a `Promise<void>` would be considered truthly. And there's no runtime way to know without awaiting the promise.

https://github.com/josh/selector-observer/blob/cd822ea2e7eb9c556cefe2de26d8a6314df4c50f/lib/apply.js#L49-L51

I kinda extended `initialize` in a really sloppy way to support this return value. So I think we're boxed in.

Without adding additional hooks/features to support async hooks, I don't think this is going to be easy to do in a safe way.

GitHub's use case is mainly using the async function syntax out of convenience. I don't think we actually care about the async initialization semantics. So it's probably not worth the effort to extend.

**Comment by muan** [comment]
Ah I forgot about `InitializerCallbacks`.

> GitHub's use case is mainly using the async function syntax out of convenience. I don't think we actually care about the async initialization semantics. So it's probably not worth the effort to extend.

Fair. 🙆

**Pull request closed without merging**
